apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service-deployment
  labels:
    app: config-service-deployment
spec:
  selector:
    matchLabels:
      app: config-service-deployment
  replicas: 2
  template:
    metadata:
      labels:
        app: config-service-deployment
    spec:
      containers:
        - name: config-service
          image: matiascm/kubernetes-config-service
          ports:
            - name: config
              containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: config-service
  labels:
    app: config-service
spec:
  selector:
    app: config-service-deployment
  ports:
    - name: config
      protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer